import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Landing() {
  const navigate = useNavigate();
  const { user } = useAuth();

  return (
    <div className="landing">
      <div className="blob blob-1"></div>
      <div className="blob blob-2"></div>
      <div className="blob blob-3"></div>

      <nav className="nav">
        <div className="nav-logo">ResuMatch</div>
        <div className="nav-actions">
          {user ? (
            <button className="btn-primary" onClick={() => navigate('/app')}>Go to App →</button>
          ) : (
            <>
              <button className="btn-ghost" onClick={() => navigate('/auth')}>Sign In</button>
              <button className="btn-primary" onClick={() => navigate('/auth')}>Get Started Free</button>
            </>
          )}
        </div>
      </nav>

      <div className="hero">
        <div className="hero-badge">🤖 Powered by Groq · Gemini · OpenAI</div>
        <h1 className="hero-title">
          Know Your Resume Score<br />
          <span className="gradient-text">Before the Recruiter Does</span>
        </h1>
        <p className="hero-subtitle">
          Upload your resume, paste any job description, and get an instant AI match score
          with missing keywords and actionable suggestions — in under 10 seconds.
        </p>
        <button className="btn-primary btn-large" onClick={() => navigate('/auth')}>
          Analyze My Resume →
        </button>

        <div className="stats">
          <div className="stat-item">
            <span className="stat-number">3</span>
            <span className="stat-label">AI Models</span>
          </div>
          <div className="stat-divider"></div>
          <div className="stat-item">
            <span className="stat-number">&lt;10s</span>
            <span className="stat-label">Analysis Time</span>
          </div>
          <div className="stat-divider"></div>
          <div className="stat-item">
            <span className="stat-number">100%</span>
            <span className="stat-label">Free to Use</span>
          </div>
        </div>
      </div>

      <div className="features">
        <div className="glass-card feature-card">
          <div className="feature-icon">📊</div>
          <h3>Match Score</h3>
          <p>Get a precise 0–100% score showing how well your resume matches the job description</p>
        </div>
        <div className="glass-card feature-card">
          <div className="feature-icon">🔍</div>
          <h3>Missing Keywords</h3>
          <p>See exactly which keywords recruiters are scanning for that your resume currently lacks</p>
        </div>
        <div className="glass-card feature-card">
          <div className="feature-icon">💡</div>
          <h3>AI Suggestions</h3>
          <p>Get specific, actionable improvements generated by AI to boost your match score instantly</p>
        </div>
      </div>
    </div>
  );
}